/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=crates/worker/wrangler.production.jsonc --include-runtime=false crates/worker/service/env.d.ts` (hash: 9f01ce33f4773e383bba850b53c4892c)
interface __BaseEnv_Env {
  VAULT_BLOBS: R2Bucket;
  DB: D1Database;
  ENROLLMENT_EMAIL: SendEmail;
  LOGOUT_QUEUE: Queue;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  MIKAKI_WAITLIST_FROM: 'no-reply@mikaki.org';
  MIKAKI_ISSUER: 'https://auth.mikaki.org';
  MIKAKI_ANDROID_SHA256_CERT_FINGERPRINT: 'FC:51:38:FE:5C:6E:05:55:AD:08:5E:4D:68:DA:F9:DB:F6:76:93:63:1E:72:C9:41:A1:7D:17:80:0D:EB:00:66';
  OP_PRIVATE_JWK: string;
  MIKAKI_READY_TOKEN: string;
  WAITLIST_MAIL_KEY: string;
  USERINFO_CLAIMS: Fetcher /* mikaki-auth-claims */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./entrypoint');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'MIKAKI_WAITLIST_FROM'
      | 'MIKAKI_ISSUER'
      | 'MIKAKI_ANDROID_SHA256_CERT_FINGERPRINT'
      | 'OP_PRIVATE_JWK'
      | 'MIKAKI_READY_TOKEN'
      | 'WAITLIST_MAIL_KEY'
    >
  > {}
}
declare module '*.sql' {
  const value: string;
  export default value;
}
declare module '*.txt' {
  const value: string;
  export default value;
}
declare module '*.html' {
  const value: string;
  export default value;
}
declare module '*.bin' {
  const value: ArrayBuffer;
  export default value;
}
declare module '*.wasm' {
  const value: WebAssembly.Module;
  export default value;
}
declare module '*.wasm?module' {
  const value: WebAssembly.Module;
  export default value;
}
