/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=crates/helpdesk-rp/wrangler.example.jsonc --include-runtime=false --strict-vars=false --env-interface=HelpdeskEnv crates/helpdesk-rp/worker-configuration.d.ts` (hash: 91c3eaeccb29ac0f4d69a25f01fbc2e3)
interface __BaseEnv_HelpdeskEnv {
	DB: D1Database;
	ISSUER: string;
	RP_ORIGIN: string;
	CLIENT_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_HelpdeskEnv {}
}
interface HelpdeskEnv extends __BaseEnv_HelpdeskEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ISSUER" | "RP_ORIGIN" | "CLIENT_ID">> {}
}
