/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=crates/helpdesk-rp/wrangler.demo.jsonc --include-runtime=false --strict-vars=false --env-interface=HelpdeskDemoEnv crates/helpdesk-rp/worker-demo-configuration.d.ts` (hash: f3cbbae48b26789083eaadca2b98ac68)
interface __BaseEnv_HelpdeskDemoEnv {
	DB: D1Database;
	DEMO_LIMITER: RateLimit;
	ISSUER: string;
	RP_ORIGIN: string;
	CLIENT_ID: string;
	DEMO_ONLY: string;
	RP_PRIVATE_JWK: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_HelpdeskDemoEnv {}
}
interface HelpdeskDemoEnv extends __BaseEnv_HelpdeskDemoEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ISSUER" | "RP_ORIGIN" | "CLIENT_ID" | "DEMO_ONLY" | "RP_PRIVATE_JWK">> {}
}
