/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/mikaki-docs/wrangler.production.jsonc --include-runtime=false --strict-vars=false --env-interface=DocsEnv apps/mikaki-docs/worker-configuration.d.ts` (hash: 5791a6617dff9315db140e0756cbb2b3)
interface __BaseEnv_DocsEnv {
  DB: D1Database;
  AUTH_LIMITER: RateLimit;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  DOCS_ASSETS: Fetcher;
  ISSUER: string;
  RP_ORIGIN: string;
  CLIENT_ID: string;
  RP_PRIVATE_JWK: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface Env extends __BaseEnv_DocsEnv {}
}
interface DocsEnv extends __BaseEnv_DocsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'ISSUER' | 'RP_ORIGIN' | 'CLIENT_ID' | 'RP_PRIVATE_JWK'>
  > {}
}
