"""Independent optional algorithm and Android Key vectors, generated by OpenSSL/Python.
Private keys stay in memory. No official suite implementation or vectors are used.
"""
import base64, copy, datetime as dt, hashlib, json, pathlib
import cbor2
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa, padding
from cryptography.x509.oid import NameOID, ObjectIdentifier
B=lambda b:base64.urlsafe_b64encode(b).decode().rstrip('=')
DER=serialization.Encoding.DER
NOW=1790035200
start=dt.datetime(2026,1,1,tzinfo=dt.timezone.utc)
end=dt.datetime(2030,1,1,tzinfo=dt.timezone.utc)
challenge=B(bytes([3])*32)
client=json.dumps({'type':'webauthn.create','challenge':challenge,'origin':'https://login.example'},separators=(',',':')).encode()
client_assert=client.replace(b'webauthn.create',b'webauthn.get')
aaguid=bytes([9])*16
rp=hashlib.sha256(b'login.example').digest()
header=rp+b'\x45'+bytes(4)
name=lambda s:x509.Name([x509.NameAttribute(NameOID.COMMON_NAME,s)])
rootkey=ec.generate_private_key(ec.SECP256R1())
rootname=name('Independent optional root')
leafname=x509.Name([x509.NameAttribute(NameOID.COUNTRY_NAME,'US'),x509.NameAttribute(NameOID.ORGANIZATION_NAME,'Mikaki'),x509.NameAttribute(NameOID.ORGANIZATIONAL_UNIT_NAME,'Authenticator Attestation'),x509.NameAttribute(NameOID.COMMON_NAME,'Optional key')])
def cert(key,ext=None,issuer=rootname,signer=rootkey,subject=leafname,ca=False):
    b=x509.CertificateBuilder().subject_name(subject).issuer_name(issuer).public_key(key.public_key()).serial_number(x509.random_serial_number()).not_valid_before(start).not_valid_after(end).add_extension(x509.BasicConstraints(ca=ca,path_length=None),True)
    if ext is not None:b=b.add_extension(x509.UnrecognizedExtension(ObjectIdentifier('1.3.6.1.4.1.11129.2.1.17'),ext),False)
    return b.sign(signer,hashes.SHA256()).public_bytes(DER)
root=cert(rootkey,subject=rootname,ca=True)
registrations=[];assertions=[]
def context(alg):return {'challenge':challenge,'origin':'https://login.example','rp_id':'login.example','max_bytes':65536,'max_depth':8,'algorithms':[alg],'attestation':{'now':NOW,'entries':[{'aaguid':B(aaguid),'roots':[B(root)],'types':['basic_full'],'allowed':True}]}}
def add(label,ok,fmt,stmt,auth,ctx):registrations.append({'name':label,'ok':ok,'context':copy.deepcopy(ctx),'response':{'id':B(b'123'),'client_data':B(client),'attestation':B(cbor2.dumps({'fmt':fmt,'attStmt':stmt,'authData':auth}))}})
def addassert(label,ok,sig,keydata,ctx):assertions.append({'name':label,'ok':ok,'context':copy.deepcopy(ctx),'stored':{'id':B(b'123'),'public_key':B(cbor2.dumps(keydata)),'user_handle':B(b'user'),'counter':0,'backup_eligible':False,'backup_state':False},'response':{'id':B(b'123'),'client_data':B(client_assert),'authenticator_data':B(rp+b'\x05'+b'\x00\x00\x00\x01'),'signature':B(sig),'user_handle':B(b'user')}})
keys={};auths={}
for alg,curve,crv,size,h in [(-35,ec.SECP384R1(),2,48,hashes.SHA384()),(-36,ec.SECP521R1(),3,66,hashes.SHA512()),(-47,ec.SECP256K1(),8,32,hashes.SHA256()),(-37,None,None,None,hashes.SHA256()),(-38,None,None,None,hashes.SHA384()),(-39,None,None,None,hashes.SHA512()),(-258,None,None,None,hashes.SHA384()),(-259,None,None,None,hashes.SHA512())]:
    k=ec.generate_private_key(curve) if curve else rsa.generate_private_key(public_exponent=65537,key_size=2048)
    n=k.public_key().public_numbers()
    ck={1:2,3:alg,-1:crv,-2:n.x.to_bytes(size,'big'),-3:n.y.to_bytes(size,'big')} if curve else {1:3,3:alg,-1:n.n.to_bytes(256,'big'),-2:n.e.to_bytes(3,'big')}
    auth=header+aaguid+b'\x00\x03123'+cbor2.dumps(ck);ctx=context(alg)
    def sign(data,salt=None,mgf=None):
        if curve:return k.sign(data,ec.ECDSA(h))
        pad=padding.PSS(mgf=padding.MGF1(mgf or h),salt_length=h.digest_size if salt is None else salt) if alg in [-37,-38,-39] else padding.PKCS1v15()
        return k.sign(data,pad,h)
    message=auth+hashlib.sha256(client).digest();sig=sign(message)
    add(str(alg)+' self',True,'packed',{'alg':alg,'sig':sig},auth,ctx)
    add(str(alg)+' bad signature',False,'packed',{'alg':alg,'sig':sig[:-1]+bytes([sig[-1]^1])},auth,ctx)
    add(str(alg)+' certificate',True,'packed',{'alg':alg,'sig':sig,'x5c':[cert(k)]},auth,ctx)
    disabled=copy.deepcopy(ctx);disabled['algorithms']=[-7];add(str(alg)+' disabled',False,'packed',{'alg':alg,'sig':sig},auth,disabled)
    wrong=copy.deepcopy(ck)
    if curve:wrong[-1]=1 if crv!=1 else 2
    else:wrong[-3]=b'private'
    add(str(alg)+' invalid key',False,'packed',{'alg':alg,'sig':sig},header+aaguid+b'\x00\x03123'+cbor2.dumps(wrong),ctx)
    amessage=rp+b'\x05'+b'\x00\x00\x00\x01'+hashlib.sha256(client_assert).digest()
    asig=sign(amessage);addassert(str(alg)+' assertion',True,asig,ck,ctx);addassert(str(alg)+' bad assertion',False,asig[:-1],ck,ctx)
    if alg in [-37,-38,-39]:
        add(str(alg)+' wrong salt',False,'packed',{'alg':alg,'sig':sign(message,salt=0)},auth,ctx)
        add(str(alg)+' wrong MGF',False,'packed',{'alg':alg,'sig':sign(message,mgf=hashes.SHA1())},auth,ctx)
        addassert(str(alg)+' wrong assertion salt',False,sign(amessage,salt=0),ck,ctx)
    keys[alg]=k;auths[alg]=auth
# Minimal DER serialization is independent of the Rust decoder.
def tlv(tag,value):
    n=len(value);length=bytes([n]) if n<128 else bytes([0x80+(n.bit_length()+7)//8])+n.to_bytes((n.bit_length()+7)//8,'big')
    return tag+length+value
seq=lambda v:tlv(b'\x30',v)
def integer(n):
    v=n.to_bytes(max(1,(n.bit_length()+7)//8),'big');return tlv(b'\x02',(b'\x00' if v[0]&128 else b'')+v)
def tag(n):
    if n<31:return bytes([0xa0+n])
    parts=[n&127];n>>=7
    while n:parts.insert(0,0x80|(n&127));n>>=7
    return b'\xbf'+bytes(parts)
explicit=lambda n,v:tlv(tag(n),v)
purpose=lambda n:explicit(1,tlv(b'\x31',integer(n)))
origin=lambda n:explicit(702,integer(n))
normal=purpose(2)+origin(0)
def desc(sw=b'',tee=normal,hash=None):return seq(integer(3)+tlv(b'\x0a',b'\x01')+integer(4)+tlv(b'\x0a',b'\x01')+tlv(b'\x04',hash or hashlib.sha256(client).digest())+tlv(b'\x04',b'')+seq(sw)+seq(tee))
# Exercise Android certificate/credential key equality for each optional key family.
for alg,k in keys.items():
    h={-35:hashes.SHA384(),-36:hashes.SHA512(),-47:hashes.SHA256(),-37:hashes.SHA256(),-38:hashes.SHA384(),-39:hashes.SHA512(),-258:hashes.SHA384(),-259:hashes.SHA512()}[alg]
    message=auths[alg]+hashlib.sha256(client).digest()
    if alg in [-35,-36,-47]:sig=k.sign(message,ec.ECDSA(h))
    else:
        pad=padding.PSS(mgf=padding.MGF1(h),salt_length=h.digest_size) if alg in [-37,-38,-39] else padding.PKCS1v15()
        sig=k.sign(message,pad,h)
    add(str(alg)+' Android key',True,'android-key',{'alg':alg,'sig':sig,'x5c':[cert(k,desc())]},auths[alg],context(alg))
k=ec.generate_private_key(ec.SECP256R1());n=k.public_key().public_numbers();ck={1:2,3:-7,-1:1,-2:n.x.to_bytes(32,'big'),-3:n.y.to_bytes(32,'big')}
auth=header+aaguid+b'\x00\x03123'+cbor2.dumps(ck);message=auth+hashlib.sha256(client).digest();ctx=context(-7)
def android(label,ok,extension,certkey=k,signkey=k,chain=None):
    add(label,ok,'android-key',{'alg':-7,'sig':signkey.sign(message,ec.ECDSA(hashes.SHA256())),'x5c':chain or [cert(certkey,extension)]},auth,ctx)
android('Android tee',True,desc())
android('Android software',True,desc(sw=normal,tee=b''))
android('Android union',True,desc(sw=purpose(2),tee=origin(0)))
android('Android wrong challenge',False,desc(hash=bytes(32)))
android('Android allApplications software',False,desc(sw=explicit(600,b'\x05\x00')))
android('Android allApplications tee',False,desc(tee=purpose(2)+explicit(600,b'\x05\x00')+origin(0)))
android('Android imported origin',False,desc(tee=purpose(2)+origin(2)))
android('Android conflicting origin',False,desc(sw=origin(2)))
android('Android no purpose',False,desc(tee=origin(0)))
android('Android wrong purpose',False,desc(tee=purpose(0)+origin(0)))
android('Android no origin',False,desc(tee=purpose(2)))
android('Android duplicate tag',False,desc(tee=purpose(2)+origin(0)+origin(0)))
android('Android trailing DER',False,desc()+b'\x00')
android('Android truncated DER',False,desc()[:-1])
android('Android extension missing',False,None)
other=ec.generate_private_key(ec.SECP256R1())
android('Android certificate key mismatch',False,desc(),certkey=other,signkey=other)
android('Android signature mismatch',False,desc(),signkey=other)
parentkey=ec.generate_private_key(ec.SECP256R1());parentname=name('Extended Android issuer');parent=cert(parentkey,desc(),subject=parentname,ca=True)
android('Android extended attestation chain',False,desc(),chain=[cert(k,desc(),issuer=parentname,signer=parentkey),parent])
p=pathlib.Path(__file__).with_name('optional.json');p.write_text(json.dumps({'registrations':registrations,'assertions':assertions},separators=(',',':'))+'\n');print(len(registrations),len(assertions),p.stat().st_size)
