/** Compile exact product Agent SQL into an OP-owned capability catalog. */
import { format } from 'prettier';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { staticSql } from './static-sql.ts';

const files = ['store', 'oauth', 'record-proposals', 'model'].map((name) =>
  resolve('crates/agent-worker/' + name + '.ts'),
);
const queries: Record<string, string> = {};
for (const sql of staticSql(files)) {
  for (const mutation of sql.matchAll(
    /\b(?:INSERT(?: OR [A-Z]+)? INTO|UPDATE(?!\s+SET\b)|DELETE FROM)\s+([a-z_]+)/gi,
  )) {
    if (!mutation[1].startsWith('agent_'))
      throw new Error('Agent cannot mutate OP-owned table: ' + mutation[1]);
  }
  if (!/^\s*(SELECT|INSERT|UPDATE|DELETE|WITH)\b/i.test(sql) || sql.includes(';'))
    throw new Error('Only one catalogued domain statement is allowed: ' + sql.slice(0, 200));
  queries[createHash('sha256').update(sql).digest('hex')] = sql;
}
const output = await format(
  '// Generated by scripts/build-service-catalog.ts; review every capability change.\nexport const agentQueries: Record<string, string> = ' +
    JSON.stringify(Object.fromEntries(Object.entries(queries).sort()), null, 2) +
    ';\n',
  { parser: 'typescript', singleQuote: true },
);
const destination = 'crates/worker/service/agent-catalog.ts';
if (process.argv.includes('--check')) {
  if ((await readFile(destination, 'utf8')) !== output)
    throw new Error('Agent capability catalog is stale; run node scripts/build-service-catalog.ts');
} else await writeFile(destination, output);
console.log('Agent store: ' + Object.keys(queries).length + ' static product statements');
