//! Native HAIP wallet protocol core. No HTTP, IPC, key export or attester issuance.
//! Callers pin issuer/client/callback and provision independent attester trust.
use crate::{client_attestation, issuance::PublicJwk, key_attestation};
use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD as B64};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use url::Url;
use zeroize::{Zeroize, Zeroizing};

pub trait Signer {
    fn public(&self) -> Result<PublicJwk, String>;
    fn sign(&self, header: Value, claims: Value) -> Result<String, String>;
}
enum Phase {
    Par,
    Browser {
        until: u64,
    },
    Code(Zeroizing<String>),
    Token {
        access: Zeroizing<String>,
        until: u64,
    },
    Closed,
}
pub struct Authorization {
    issuer: Url,
    client: String,
    callback: Url,
    configuration: String,
    state: Zeroizing<String>,
    verifier: Zeroizing<String>,
    instance: PublicJwk,
    dpop: PublicJwk,
    holder: Option<PublicJwk>,
    until: u64,
    phase: Phase,
}
fn opaque(s: &str) -> bool {
    s.len() == 43
        && s.bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'-' | b'_'))
}
fn https(s: &str) -> Result<Url, String> {
    let u = Url::parse(s).map_err(|_| "wallet_configuration_invalid")?;
    if s.len() > 2048
        || u.as_str() != s
        || u.scheme() != "https"
        || u.host_str().is_none()
        || !u.username().is_empty()
        || u.password().is_some()
        || u.fragment().is_some()
    {
        return Err("wallet_configuration_invalid".into());
    }
    Ok(u)
}
impl Authorization {
    pub fn client_id(&self) -> &str {
        &self.client
    }
    pub fn enrollment_available(&self, now: u64) -> Result<(), String> {
        self.live(now)
    }
    /// Entropy is generated by the native caller. This object cannot be serialized.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        issuer: &str,
        client: &str,
        callback: &str,
        configuration: &str,
        state_entropy: [u8; 32],
        verifier_entropy: [u8; 32],
        instance: PublicJwk,
        dpop: PublicJwk,
        holder: PublicJwk,
        now: u64,
    ) -> Result<Self, String> {
        Self::new_inner(
            issuer,
            client,
            callback,
            configuration,
            state_entropy,
            verifier_entropy,
            instance,
            dpop,
            Some(holder),
            now,
        )
    }
    /// Android attestation challenges are obtained after authorization and issuer nonce.
    #[allow(clippy::too_many_arguments)]
    pub fn new_pending_holder(
        issuer: &str,
        client: &str,
        callback: &str,
        configuration: &str,
        state_entropy: [u8; 32],
        verifier_entropy: [u8; 32],
        instance: PublicJwk,
        dpop: PublicJwk,
        now: u64,
    ) -> Result<Self, String> {
        Self::new_inner(
            issuer,
            client,
            callback,
            configuration,
            state_entropy,
            verifier_entropy,
            instance,
            dpop,
            None,
            now,
        )
    }
    #[allow(clippy::too_many_arguments)]
    fn new_inner(
        issuer: &str,
        client: &str,
        callback: &str,
        configuration: &str,
        state_entropy: [u8; 32],
        verifier_entropy: [u8; 32],
        instance: PublicJwk,
        dpop: PublicJwk,
        holder: Option<PublicJwk>,
        now: u64,
    ) -> Result<Self, String> {
        let state_entropy = Zeroizing::new(state_entropy);
        let verifier_entropy = Zeroizing::new(verifier_entropy);
        let issuer = https(issuer)?;
        let callback = https(callback)?;
        if issuer.query().is_some()
            || issuer.path().ends_with('/')
            || client.is_empty()
            || client.len() > 256
            || !matches!(configuration, "linked_document" | "linked_document_mdoc")
            || *state_entropy == *verifier_entropy
            || instance == dpop
            || holder
                .as_ref()
                .is_some_and(|h| h == &instance || h == &dpop)
        {
            return Err("wallet_configuration_invalid".into());
        }
        for key in [&instance, &dpop].into_iter().chain(holder.iter()) {
            key.verifying_key().map_err(str::to_owned)?;
        }
        let mut names = std::collections::BTreeSet::new();
        if callback
            .query()
            .is_some_and(|q| q.is_empty() || q.len() > 1024)
        {
            return Err("wallet_configuration_invalid".into());
        }
        for (name, _) in callback.query_pairs() {
            if name.is_empty() || !names.insert(name.into_owned()) || names.len() > 16 {
                return Err("wallet_configuration_invalid".into());
            }
        }
        if names.iter().any(|s| {
            matches!(
                s.as_str(),
                "code" | "state" | "iss" | "error" | "error_description" | "error_uri"
            )
        }) {
            return Err("wallet_configuration_invalid".into());
        }
        Ok(Self {
            issuer,
            client: client.into(),
            callback,
            configuration: configuration.into(),
            state: Zeroizing::new(B64.encode(*state_entropy)),
            verifier: Zeroizing::new(B64.encode(*verifier_entropy)),
            instance,
            dpop,
            holder,
            until: now.saturating_add(180),
            phase: Phase::Par,
        })
    }
    pub fn holder_binding_available(&self, now: u64) -> Result<(), String> {
        self.live(now)?;
        match self.phase {
            Phase::Token { until, .. } if now < until && self.holder.is_none() => Ok(()),
            _ => Err("wallet_transaction_unavailable".into()),
        }
    }
    /// Bind the fresh attested holder once; never replace a credential key.
    pub fn bind_holder(&mut self, holder: PublicJwk, now: u64) -> Result<(), String> {
        self.holder_binding_available(now)?;
        holder.verifying_key().map_err(str::to_owned)?;
        if holder == self.instance || holder == self.dpop {
            return Err("wallet_configuration_invalid".into());
        }
        self.holder = Some(holder);
        Ok(())
    }
    fn live(&self, now: u64) -> Result<(), String> {
        if now >= self.until || matches!(self.phase, Phase::Closed) {
            Err("wallet_transaction_unavailable".into())
        } else {
            Ok(())
        }
    }
    pub fn par_parameters(&self, now: u64) -> Result<Value, String> {
        self.live(now)?;
        if !matches!(self.phase, Phase::Par) {
            return Err("wallet_transaction_unavailable".into());
        }
        Ok(
            json!({"client_id":self.client,"redirect_uri":self.callback.as_str(),"response_type":"code",
            "scope":self.configuration,"state":&*self.state,"code_challenge":B64.encode(Sha256::digest(self.verifier.as_bytes())),
            "code_challenge_method":"S256","dpop_jkt":self.dpop.thumbprint().map_err(str::to_owned)?}),
        )
    }
    pub fn accept_par(&mut self, body: &Value, now: u64) -> Result<Url, String> {
        self.live(now)?;
        if !matches!(self.phase, Phase::Par) {
            return Err("wallet_transaction_unavailable".into());
        }
        let uri = body["request_uri"].as_str().ok_or("invalid_par_response")?;
        let lifetime = body["expires_in"]
            .as_u64()
            .filter(|n| (1..=90).contains(n))
            .ok_or("invalid_par_response")?;
        if !uri
            .strip_prefix("urn:ietf:params:oauth:request_uri:")
            .is_some_and(opaque)
        {
            return Err("invalid_par_response".into());
        }
        let mut target = Url::parse(&format!("{}/authorize", self.issuer))
            .map_err(|_| "wallet_configuration_invalid")?;
        target
            .query_pairs_mut()
            .append_pair("client_id", &self.client)
            .append_pair("request_uri", uri);
        self.phase = Phase::Browser {
            until: self.until.min(now.saturating_add(lifetime)),
        };
        Ok(target)
    }
    /// Invalid/unrelated callbacks leave the transaction pending; a valid denial closes it.
    pub fn accept_callback(&mut self, input: &str, now: u64) -> Result<bool, String> {
        self.live(now)?;
        let Phase::Browser { until } = self.phase else {
            return Err("wallet_transaction_unavailable".into());
        };
        if now >= until {
            self.cancel();
            return Err("wallet_transaction_unavailable".into());
        }
        if input.len() > 4096 {
            return Err("invalid_wallet_callback".into());
        }
        let callback = Url::parse(input).map_err(|_| "invalid_wallet_callback")?;
        let mut base = callback.clone();
        base.set_query(self.callback.query());
        if base != self.callback || callback.fragment().is_some() || callback.as_str() != input {
            return Err("invalid_wallet_callback".into());
        }
        let mut pairs = std::collections::BTreeMap::new();
        for (k, v) in callback.query_pairs() {
            if pairs.insert(k.into_owned(), v.into_owned()).is_some() || pairs.len() > 24 {
                return Err("invalid_wallet_callback".into());
            }
        }
        for (k, v) in self.callback.query_pairs() {
            if pairs.remove(k.as_ref()).as_deref() != Some(v.as_ref()) {
                return Err("invalid_wallet_callback".into());
            }
        }
        if pairs.remove("state").as_deref() != Some(self.state.as_str())
            || pairs.remove("iss").as_deref() != Some(self.issuer.as_str())
        {
            return Err("invalid_wallet_callback".into());
        }
        let code = pairs.remove("code");
        let error = pairs.remove("error");
        pairs.remove("error_description");
        pairs.remove("error_uri");
        // OAuth clients ignore unrecognized response parameters. Recognized and fixed
        // parameters above remain bound, and all decoded names must still be unique.
        if code.is_some() == error.is_some() {
            return Err("invalid_wallet_callback".into());
        }
        if let Some(error) = error {
            if error.is_empty() || error.len() > 128 {
                return Err("invalid_wallet_callback".into());
            }
            self.cancel();
            return Ok(false);
        }
        let code = code
            .filter(|s| opaque(s))
            .ok_or("invalid_wallet_callback")?;
        self.phase = Phase::Code(Zeroizing::new(code));
        Ok(true)
    }
    pub fn token_parameters(&self, now: u64) -> Result<Value, String> {
        self.live(now)?;
        let Phase::Code(code) = &self.phase else {
            return Err("wallet_transaction_unavailable".into());
        };
        Ok(
            json!({"grant_type":"authorization_code","client_id":self.client,"redirect_uri":self.callback.as_str(),
            "code":&**code,"code_verifier":&*self.verifier}),
        )
    }
    pub fn accept_token(&mut self, body: Value, now: u64) -> Result<(), String> {
        self.live(now)?;
        if !matches!(self.phase, Phase::Code(_)) {
            return Err("wallet_transaction_unavailable".into());
        }
        let access = body["access_token"]
            .as_str()
            .filter(|s| opaque(s))
            .ok_or("invalid_token_response")?;
        let lifetime = body["expires_in"]
            .as_u64()
            .filter(|n| (1..=120).contains(n))
            .ok_or("invalid_token_response")?;
        if !body["token_type"]
            .as_str()
            .is_some_and(|s| s.eq_ignore_ascii_case("DPoP"))
            || body["scope"] != self.configuration
            || body.get("refresh_token").is_some()
        {
            return Err("invalid_token_response".into());
        }
        self.phase = Phase::Token {
            access: Zeroizing::new(access.into()),
            until: self.until.min(now.saturating_add(lifetime)),
        };
        self.state.zeroize();
        self.verifier.zeroize();
        Ok(())
    }
    pub fn client_headers(
        &self,
        attestation: &str,
        policies: &[client_attestation::AttesterTrust],
        signer: &impl Signer,
        jti: &str,
        now: u64,
    ) -> Result<Value, String> {
        self.live(now)?;
        if !matches!(self.phase, Phase::Par | Phase::Code(_))
            || signer.public()? != self.instance
            || !opaque(jti)
        {
            return Err("invalid_client".into());
        }
        let pop = signer.sign(json!({"typ":"oauth-client-attestation-pop+jwt","alg":"ES256"}),
            json!({"iss":self.client,"aud":self.issuer.as_str(),"iat":now,"exp":now.saturating_add(90),"jti":jti}))?;
        let verified = client_attestation::verify(
            attestation,
            &pop,
            &self.client,
            self.issuer.as_str(),
            policies,
            now,
        )
        .map_err(str::to_owned)?;
        if verified.thumbprint != self.instance.thumbprint().map_err(str::to_owned)? {
            return Err("invalid_client".into());
        }
        Ok(json!({"OAuth-Client-Attestation":attestation,"OAuth-Client-Attestation-PoP":pop}))
    }
    pub fn dpop(
        &self,
        endpoint: &str,
        nonce: Option<&str>,
        signer: &impl Signer,
        jti: &str,
        now: u64,
    ) -> Result<String, String> {
        self.live(now)?;
        if signer.public()? != self.dpop
            || !opaque(jti)
            || nonce.is_some_and(|n| n.is_empty() || n.len() > 128)
        {
            return Err("invalid_dpop_proof".into());
        }
        let mut claims =
            json!({"htu":format!("{}/{endpoint}",self.issuer),"htm":"POST","iat":now,"jti":jti});
        match (&self.phase, endpoint) {
            (Phase::Par, "par") | (Phase::Code(_), "token") => {}
            (Phase::Token { access, until }, "credential") if now < *until => {
                claims["ath"] = Value::String(B64.encode(Sha256::digest(access.as_bytes())));
            }
            _ => return Err("wallet_transaction_unavailable".into()),
        }
        if let Some(nonce) = nonce {
            claims["nonce"] = Value::String(nonce.into());
        }
        signer.sign(
            json!({"typ":"dpop+jwt","alg":"ES256","jwk":self.dpop}),
            claims,
        )
    }
    pub fn credential_request(
        &self,
        nonce: &str,
        attestation: &str,
        trust: &key_attestation::Trust,
        signer: &impl Signer,
        now: u64,
    ) -> Result<Value, String> {
        self.live(now)?;
        let Phase::Token { until, .. } = self.phase else {
            return Err("wallet_transaction_unavailable".into());
        };
        let holder = self
            .holder
            .as_ref()
            .ok_or("wallet_transaction_unavailable")?;
        if now >= until || &signer.public()? != holder {
            return Err("wallet_transaction_unavailable".into());
        }
        let verified =
            key_attestation::verify(attestation, nonce, trust, true, now).map_err(str::to_owned)?;
        if &verified.holder != holder {
            return Err("invalid_proof".into());
        }
        let header = json!({"typ":"openid4vci-proof+jwt","alg":"ES256","jwk":holder,"key_attestation":attestation});
        let claims = json!({"iss":self.client,"aud":self.issuer.as_str(),"iat":now,"nonce":nonce});
        // Match the native Keystore signing-input bound, including JWT base64 overhead.
        let h = serde_json::to_vec(&header).map_err(|_| "invalid_proof")?;
        let c = serde_json::to_vec(&claims).map_err(|_| "invalid_proof")?;
        if B64.encode(h).len() + 1 + B64.encode(c).len() > 16384 {
            return Err("invalid_proof".into());
        }
        let proof = signer.sign(header, claims)?;
        Ok(json!({"credential_configuration_id":self.configuration,"proofs":{"jwt":[proof]}}))
    }
    pub fn authorization_header(&self, now: u64) -> Result<Zeroizing<String>, String> {
        self.live(now)?;
        match &self.phase {
            Phase::Token { access, until } if now < *until => {
                Ok(Zeroizing::new(format!("DPoP {}", **access)))
            }
            _ => Err("wallet_transaction_unavailable".into()),
        }
    }
    pub fn cancel(&mut self) {
        self.phase = Phase::Closed;
        self.state.zeroize();
        self.verifier.zeroize();
    }
}
