/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=crates/agent-worker/wrangler.local.jsonc --include-runtime=false --strict-vars=false crates/agent-worker/env.d.ts` (hash: 666b74dca17855276504b5ef1acbbb44)
interface __BaseEnv_Env {
	DB: D1Database;
	AGENT_RESOURCE: string;
	AGENT_OWNER_URL: string;
	AGENT_PRIVATE_JWK: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENT_RESOURCE" | "AGENT_OWNER_URL" | "AGENT_PRIVATE_JWK">> {}
}
