/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=crates/agent-worker/wrangler.example.jsonc --include-runtime=false --strict-vars=false crates/agent-worker/env.d.ts` (hash: f85dbdd1bd81ee922c20c9cf2134b3d8)
interface __BaseEnv_Env {
	AGENT_RESOURCE: string;
	AGENT_OWNER_URL: string;
	AGENT_PRIVATE_JWK: string;
	AUTH_STORE: Service /* entrypoint AgentStore from mikaki-op */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENT_RESOURCE" | "AGENT_OWNER_URL" | "AGENT_PRIVATE_JWK">> {}
}
