/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=website/wrangler.app.jsonc --include-runtime=false website/worker-configuration.d.ts` (hash: 8aac557fa342391dc40ac4394952dcb4)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./app-worker');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
